from tkinter import*
window = Tk()
window.title("login")
window.geometry("800x800")
window.config(background = "blue")
l1 = Label(window,text = "Username",fg = "red",width = 7,height = 2,bg = "white",font = ("Ariel",20,"bold"),bd = 10,relief = "solid")
l2 = Label(window,text = "Password",fg = "red",width = 7,height = 2,bg = "white",font = ("Ariel",20,"bold"),bd = 10,relief = "solid")
e1 = Entry(window,fg = "black",width = 8,bg = "white",font = ("Ariel",20,"bold"))
e2 = Entry(window,fg = "black",width = 8,bg = "white",font = ("Ariel",20,"bold"))
b1 = Button(window,text = "Login",bg = "white",fg = "red",activebackground = "blue",activeforeground = "yellow",font = ("Ariel",20,"bold"),width = 3,height = 2,bd = 10,relief = "solid")
l1.place(x = 300,y = 300)
l2.place(x = 300,y = 400)
e1.place(x = 600,y = 300)
e2.place(x = 600,y = 400)
b1.place(x = 400,y = 700)
window.mainloop()
