from tkinter import *
window = Tk()
window.title("Registration form")
window.geometry("1100x1100")
l1 = Label(window,text = "Registration form",fg = "red",width = 10,height = 3,bg = "white",font = ("Ariel",20,"bold"),bd = 10,relief = "solid")
l2 = Label(window,text = "Full name",fg = "red",width = 5,height = 1,bg = "white",font = ("Ariel",20,"bold"),bd = 10,relief = "solid")
l3 = Label(window,text = "Email",fg = "red",width = 5,height = 1,bg = "white",font = ("Ariel",20,"bold"),bd = 10,relief = "solid")
l4 = Label(window,text = "DOB",fg = "red",width = 5,height = 1,bg = "white",font = ("Ariel",20,"bold"),bd = 10,relief = "solid")
l5 = Label(window,text = "Gender",fg = "red",width = 5,height = 1,bg = "white",font = ("Ariel",20,"bold"),bd = 10,relief = "solid")
l6 = Label(window,text = "Contact no.",fg = "red",width = 5,height = 1,bg = "white",font = ("Ariel",10,"bold"),bd = 10,relief = "solid")
l7 = Label(window,text = "Select course",fg = "red",width = 5,height = 1,bg = "white",font = ("Ariel",10,"bold"),bd = 10,relief = "solid")
e1 = Entry(window,fg = "black",width = 8,bg = "white",font = ("Ariel",20,"bold"))
e2 = Entry(window,fg = "black",width = 8,bg = "white",font = ("Ariel",20,"bold"))
e3 = Entry(window,fg = "black",width = 8,bg = "white",font = ("Ariel",20,"bold"))
e4 = Entry(window,fg = "black",width = 8,bg = "white",font = ("Ariel",20,"bold"))
e5 = Entry(window,fg = "black",width = 8,bg = "white",font = ("Ariel",20,"bold"))
e6 = Entry(window,fg = "black",width = 8,bg = "white",font = ("Ariel",20,"bold"))
b1 = Button(window,text = "Submit",bg = "white",fg = "red",activebackground = "blue",activeforeground = "yellow",font = ("Ariel",10,"bold"),width = 1,height = 1,bd = 10,relief = "solid")
b2 = Button(window,text = "Cancel",bg = "white",fg = "red",activebackground = "blue",activeforeground = "yellow",font = ("Ariel",10,"bold"),width = 1,height = 1,bd = 10,relief = "solid")
l1.place(x = 400,y = 100)
l2.place(x = 300,y = 300)
l3.place(x = 300,y = 400)
l4.place(x = 300,y = 500)
l5.place(x = 300,y = 600)
l6.place(x = 300,y = 700)
l7.place(x = 300,y = 800)
e1.place(x = 500,y = 300)
e2.place(x = 500,y = 400)
e3.place(x = 500,y = 500)
e4.place(x = 500,y = 600)
e5.place(x = 500,y = 700)
e6.place(x = 500,y = 800)
b1.place(x = 700,y = 100)
b2.place(x = 800,y = 100)
window.mainloop()