from tkinter import*
window  = Tk()
window.title("Calender")
window.geometry("800x800")
l1 = Label(window,text = "CALENDER",fg = "white",bg = "grey",width =20,height = 3,font = ("Ariel",20,"bold"),bd = 1,relief = "solid")
l2 = Label(window,text = "Enter year",fg = "white",bg = "green",width = 10,height = 1,font = ("Ariel",20,"bold"),bd = 1,relief = "solid")
e1 = Entry(window)
b1 = Button(window,text = "Show calender",fg = "black",bg = "white",activebackground = "white",activeforeground = "black",width = 8,height = 2,font = ("Ariel",10,"bold"),bd = 1)
b2 = Button(window,text = "Submit",fg = "black",bg = "white",activebackground = "white",activeforeground = "black",width = 8,height = 2,font = ("Ariel",10,"bold"),bd = 1)
l1.place(x = 150,y = 200)
l2.place(x = 250,y = 350)
e1.place(x = 250,y = 400)
b1.place(x = 300,y = 500)
b2.place(x = 300,y = 600)
window.mainloop()